# **DSCI 100 Planning Stage Proposal**

In [13]:
# import libraries!
library(tidyverse)
library(repr)
library(tidymodels)
library(GGally)
library(ISLR)

getwd()

[1] "/home/jovyan/work/dsci-100-individual-planning"

In [17]:
# read in the data
sessions_data <- read_csv("sessions.csv")

players_data <- read_csv("players.csv")

# check structure and summary
glimpse(sessions_data)
summary(sessions_data)
glimpse(players_data)
summary(players_data)

# count missing values
colSums(is.na(sessions_data))
colSums(is.na(players_data))

#In this assignment, you will:
#- Do the minimum necessary wrangling to turn your data into a tidy format. Do not do any additional wrangling here; that will happen later during the group project phase.
#- Make a few exploratory visualizations of the data to help you understand it.
#- Use our visualization best practices to make high-quality plots (make sure to include labels, titles, units of measurement, etc)
#- Explain any insights you gain from these plots that are relevant to address your question

ERROR: Error: 'sessions.csv' does not exist in current working directory ('/home/jovyan/work/dsci-100-individual-planning').


In [20]:
# Here are the averages for the appropriate values which can have calculated averages from the players dataset.

players_table <- data.frame(
    Variable = c("Average Age", "Average Hours"),
    Value = c(21.14, 5.85))
players_table

Variable      Value
1 Average Age   21.14
2 Average Hours  5.85

### **Data Description**
We can observe that for players.csv, there is a total of 196 players. There are a total of 7 variables, including the following and their options/style of option:
- age (numeric)
- gender (Male, Female, Prefer not to say, Two-Spirited, Non-binary, Other)
- name (alphabetical)
- hours played (played_hours and numeric)
- hashedEmail (combination of letters and numbers)
- experience (Beginner, Amateur, Regular, Pro, Veteran)
- whether or not they are subscribed (subscribe and binary with TRUE or FALSE)

The average age appears to be 21.14 years old, with 144 subscribed and 52 not subscribed. The average hours played appears to be about 5.85 hours. Most of these variables are likely to be helpful, although having both the name and hashedEmail does not appear to be helpful to use together given they serve the same purpose of identification. 


We can observe that for sessions.csv, there is a total count of 1,535 observations. There are a total of 5 variables, including the following and their options/style of option:
- hashedEmail (combination of letters and numbers)
- Session Start Time (start_time in the format of DD/MM/YY - 24:00)
- Session End Time (end_time in the same format as the start time above)
- Original Start Time (original_start_time taking milliseconds since 01/01/1970)
- Original End Time (original_end_time taking the same formatting as original start time)

The average original start time is is about 1.72e+12, and the average original end time is about the same given how large the numbers are. These are unlikely to be helpful variables, given there is often no discrepancy found between them. Isolating the start and end times would be much better by tidying them. 


### **Question**

The broad question of interest I will be attempting to address is Question 3: 
- We are interested in demand forecasting, namely, what time windows are most likely to have large number of simultaneous players. This is because we need to ensure that the number of licenses on hand is sufficiently large to accommodate all parallel players with high probability.

The specific question I will be attempting to solve is as follows: Can the age of a player predict total playtime in the dataset? 

This dataset allows me to analyze how age relates to engagement. To address this, I will need to clean the data by removing missing or invalid age values and filteroug out potential outliers in playtime. Then, I will create a dataset where observations represent a player with an age and their total playtime. Through this, I can visualize the relationship and then use a simple linear regression model to test whether player age predicts total playtime. The model will thus show whether age is significantly associated with how long players spend in the game.

### **Methods & Plans**

I will be using a simple linear regression to model the relationship between player age (explanatory variable) and total playtime (response variable). This is suitable because both variables are continuous, and the goal is to test whether age can predict total playtime. It provides interpretable coefficients which indicate the direction and strength of the relationship, and helps quantify how much playtime changes with age. 

We must assume that a linear relationship exists between age and total playtime, that observations are independent, and that there are no influential outliers that affect the model. 
Some notable limitations are that linear regression cannot capture nonlinear or complex patterns between age and playtime. 

Additionally, it is sensitive to outliers. We must also note that correlation does not imply causation, so results only show association, not influence. 

I will use simple linear regression to predict total playtime from age. Linear regression is ideal because the response variable is continuous, and the explanatory variable is also numeric. KNN could also be used, but for a single predictor and a simple, interpretable relationship, linear regression would be preferred. 

Before modeling, I will clean the data by removing missing or unrealistic values (ie. negative age or playtime). The dataset will then be randomly split into a training (70%) and testing (%30) subset to avoid overfitting. The model will be trained with the training set, and predictive accuracy will be evaluated on the test set with the RMSE metric. If neecessary, k-fold cross-validation within the training data can help ensure model stability (could use k = 5).